function [afe_features] = extract_features(ads, fs)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
ms = 30;
w = round((ms/1000) * fs);
window = ones(w,1);
op = 0.5;
overlap = round(w*op);
afe = audioFeatureExtractor("SampleRate", fs, ...
                            "SpectralDescriptorInput","melSpectrum", ...
                            "Window", window, ...
                            "OverlapLength", overlap, ... 
                            "spectralCentroid", true, ...
                            "spectralKurtosis", true, ...
                            "spectralSkewness", true, ...
                            "spectralFlux", false, ...
                            "spectralSlope", false, ...
                            "mfcc", true, ...
                            "mfccDelta", false, ...
                            "mfccDeltaDelta", false, ...
                            "harmonicRatio", true, ...
                            "pitch",true);
                        
for f = 1:length(ads.UnderlyingDatastore.Files)
    file = read(ads);
    afe_features{1,f} = extract(afe,file);
    [~,c] = size(afe_features{1,f});
    i = 1;
    for s = 1:floor(length(file)/overlap)-1
        afe_features{1,f}(i,c+1) = short_time_energy(file(overlap*(s-1)+1:overlap*(s+1)));
        afe_features{1,f}(i,c+2) = zcr(file(overlap*(s-1)+1:overlap*(s+1)));
        i = i + 1;
    end
end

