function [features] = extract_features(ads, fs)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
ms = 30;
w = round((ms/1000) * fs);
window = ones(1024,1);
op = 0.5;
overlap = round(w*op);
afe = audioFeatureExtractor("SampleRate", fs, ...
                            "SpectralDescriptorInput","melSpectrum", ...
                            "Window", window, ...
                            "OverlapLength", overlap, ... 
                            "spectralCentroid",true, ...
                            "spectralKurtosis", true, ...
                            "spectralSlope", true, ...
                            "spectralFlux", true, ...
                            "spectralSpread", true, ...
                            "mfcc", true, ...
                            "mfccDelta", true, ...
                            "mfccDeltaDelta", true, ...
                            "harmonicRatio", true, ...
                            "pitch",true);
for f = 1:length(ads.UnderlyingDatastore.Files)                       
    features{f} = extract(afe,read(ads));
end

